# Generated by Django 4.1.3 on 2022-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_courseteacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='img_source',
            field=models.FilePathField(default='NULL', verbose_name='Путь к медиа'),
        ),
        migrations.AlterField(
            model_name='news',
            name='preamble',
            field=models.CharField(max_length=1024, verbose_name='Описание'),
        ),
    ]
