"""
Django settings for Braniac project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-3w81g*qn%z%m68_fy#fu2i!vo43gs%2_*!$_2gb%r6k!i^$ozq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'markdownify.apps.MarkdownifyConfig',
    'crispy_forms',
    'debug_toolbar',
    'mainapp',
    'authapp',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',

]

ROOT_URLCONF = 'Braniac.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['base_templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',  # добавляет переменную debug
                'django.template.context_processors.request',  # добавляет в контекст обьект запроса
                'django.template.context_processors.media',  # довавили, пока непонятно для чего
                'django.contrib.auth.context_processors.auth',  # добавляет user и perms  (permissions)
                'django.contrib.messages.context_processors.messages',  # messages - список сообщений
                'mainapp.context_processors.mainapp_cp.some_data_func',  # наш контекстный процессор
            ],
        },
    },
]

WSGI_APPLICATION = 'Braniac.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static').replace("\\", "/"),
]

STATIC_URL = 'static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / '/media/'

AUTH_USER_MODEL = 'authapp.CustomUser'

LOGIN_REDIRECT_URL = '/'

LOGOUT_REDIRECT_URL = '/'

MESSAGE_STORAGE = 'django.contrib.messages.storage.session.SessionStorage'

CRISPY_TEMPLATE_PACK = "bootstrap4"  # указываем какой css слить используем

LOG_FILE = BASE_DIR / 'log' / 'main_log.log'  # файл для логов

LOGGING = {
    'version': 1,  # версия конфигуратора, если 1 - используется словарь
    'disable_existing_loggers': False,  # отключать ли остальные логгеры
    'formatters': {  # как и в каком формате выводить лог
        'console': {  # имя форматтера
            'format': '[%(asctime)s] %(levelname)s %(name)s {%(thread)d} %(message)s'
            # порядок вывода, время/уровень/имя модуля/строка/сообщение
        },
    },
    'handlers': {  # обработчик/куда выводить лог
        'file': {
            'level': 'DEBUG',
            'class': 'logging.FileHandler',
            'filename': LOG_FILE,
            'formatter': 'console'
        },
        'console': {  # имя обработчика
            'class': 'logging.StreamHandler', 'formatter': 'console'  # класс вывода потока сообщений/формат потока
        },
    },

    'loggers': {  # логгер реализует настройку взаимодействия форматтера и обработчика #TODO
        'django': {'level': 'INFO', 'handlers': ['file']},  # видимо откуда и куда идет лог, тут сама django
        'mainapp': {  # с майнапп сообщения будут выводится только в файл, в консоль пойдет заглушка.
            'level': 'DEBUG',
            'handlers': ['console']
        }
    }

}

ALLOWED_HOSTS = ['*']

INTERNAL_IPS = ['127.0.0.1', '192.168.1.100']

# 6379
CACHES = {
    'default': {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://localhost:6379",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        },
    },
}

CELERY_BROKER_URL = 'redis://localhost:6379'  # указание на брокер
CELERY_RESULT_BACKEND = 'redis://localhost:6379'  # указание бекенда для результатов выполнения задач

# Read about sending email:
# https://docs.djangoproject.com/en/3.2/topics/email/
# Full list of email settings:
# https://docs.djangoproject.com/en/3.2/ref/settings/#email
# EMAIL_HOST = "localhost"
# EMAIL_PORT = "25"
# For debugging: python -m smtpd -n -c DebuggingServer localhost:25
# EMAIL_HOST_USER = "django@geekshop.local"
# EMAIL_HOST_PASSWORD = "geekshop"
# EMAIL_USE_SSL = False
# If server support TLS:
# EMAIL_USE_TLS = True
# Email as files for debug
EMAIL_BACKEND = "django.core.mail.backends.filebased.EmailBackend"
EMAIL_FILE_PATH = "log/email-messages/"
